### ISSUE TITLE
初学C++，请教编译的问题

### ISSUE THREAD

**Issue by ganluo960214** [GamebabyRockSun/GRSDXRSamples#1]
![image](https://user-images.githubusercontent.com/8499204/102964148-e26f8d00-4525-11eb-9f66-5e251c134b67.png)
这个问题怎么解决啊？

**Comment by GamebabyRockSun** [comment]
1号示例已经修改正常了，请更新后编译就不会了

**Comment by GamebabyRockSun** [comment]
1号示例此问题已经改好了，预计后续的在本月也就改完了，因此该问题就关闭了。
